language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libusb-dev
  - sudo apt-get install -y build-essential libudev-dev libtool
  - mkdir ~/git
  - cd ~/git
  - git clone https://github.com/ktossell/libuvc
  - cd libuvc
  - mkdir build
  - cd build
  - cmake ..
  - make && sudo make install
